export const genres = [
  'Ciencia ficción',
  'Fantasía',
  'Terror',
  'Misterio',
  'Romance',
  'Thriller',
  'No ficción',
  'Biografía',
  'Historia',
  'Poesía',
  'Drama',
  'Cómics',
  'Recetario',
  'Autoayuda',
  'Viajes',
  'Niños',
  'Jóvenes adultos',
  'Arte',
  'Deportes',
  'Manualidades',
  'Religión',
  'Filosofía',
  'Psicología',
  'Educación',
  'Negocios',
  'Economía',
  'Política',
  'Sociología',
  'Antropología',
  'Medicina',
  'Tecnología',
  'Informática',
  'Ciencia',
  'Matemáticas',
  'Física',
  'Química',
  'Biología',
  'Astronomía',
  'Geología',
  'Ecología',
  'Botánica',
  'Zoología',
  'Geografía',
  'Historia del arte',
  'Arquitectura',
  'Diseño',
  'Cine',
  'Teatro',
  'Televisión',
  'Música'
];
